//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace MaSoft.MaPos.Models.MaPos
{

    public partial class CashBoxSummaryInfo : XPLiteObject
    {
        int fRowID;
        [Key(true)]
        public int RowID
        {
            get { return fRowID; }
            set { SetPropertyValue<int>(nameof(RowID), ref fRowID, value); }
        }
        DateTime fRowAddDateTime;
        public DateTime RowAddDateTime
        {
            get { return fRowAddDateTime; }
            set { SetPropertyValue<DateTime>(nameof(RowAddDateTime), ref fRowAddDateTime, value); }
        }
        int fRowAddUserNo;
        public int RowAddUserNo
        {
            get { return fRowAddUserNo; }
            set { SetPropertyValue<int>(nameof(RowAddUserNo), ref fRowAddUserNo, value); }
        }
        DateTime fRowEditDateTime;
        public DateTime RowEditDateTime
        {
            get { return fRowEditDateTime; }
            set { SetPropertyValue<DateTime>(nameof(RowEditDateTime), ref fRowEditDateTime, value); }
        }
        int fRowEditUserNo;
        public int RowEditUserNo
        {
            get { return fRowEditUserNo; }
            set { SetPropertyValue<int>(nameof(RowEditUserNo), ref fRowEditUserNo, value); }
        }
        int fCashBoxID;
        [Indexed(@"Currency", Name = @"Idx_Id", Unique = true)]
        public int CashBoxID
        {
            get { return fCashBoxID; }
            set { SetPropertyValue<int>(nameof(CashBoxID), ref fCashBoxID, value); }
        }
        float fTotalAmount;
        [ColumnDbDefaultValue("((0))")]
        public float TotalAmount
        {
            get { return fTotalAmount; }
            set { SetPropertyValue<float>(nameof(TotalAmount), ref fTotalAmount, value); }
        }
        string fCurrency;
        [Size(10)]
        public string Currency
        {
            get { return fCurrency; }
            set { SetPropertyValue<string>(nameof(Currency), ref fCurrency, value); }
        }
    }

}
