//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace MaSoft.MaPos.Models.MaPos
{

    public partial class Customers : XPLiteObject
    {
        int fRowID;
        [Key(true)]
        public int RowID
        {
            get { return fRowID; }
            set { SetPropertyValue<int>(nameof(RowID), ref fRowID, value); }
        }
        DateTime fRowAddDateTime;
        public DateTime RowAddDateTime
        {
            get { return fRowAddDateTime; }
            set { SetPropertyValue<DateTime>(nameof(RowAddDateTime), ref fRowAddDateTime, value); }
        }
        int fRowAddUserNo;
        public int RowAddUserNo
        {
            get { return fRowAddUserNo; }
            set { SetPropertyValue<int>(nameof(RowAddUserNo), ref fRowAddUserNo, value); }
        }
        DateTime fRowEditDateTime;
        public DateTime RowEditDateTime
        {
            get { return fRowEditDateTime; }
            set { SetPropertyValue<DateTime>(nameof(RowEditDateTime), ref fRowEditDateTime, value); }
        }
        int fRowEditUserNo;
        public int RowEditUserNo
        {
            get { return fRowEditUserNo; }
            set { SetPropertyValue<int>(nameof(RowEditUserNo), ref fRowEditUserNo, value); }
        }
        int fID;
        [Indexed(Name = @"UI_ID", Unique = true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }
        string fTelephone;
        [Indexed(Name = @"Idx_Tel", Unique = true)]
        [Size(50)]
        public string Telephone
        {
            get { return fTelephone; }
            set { SetPropertyValue<string>(nameof(Telephone), ref fTelephone, value); }
        }
        string fCustomerName;
        [Size(50)]
        public string CustomerName
        {
            get { return fCustomerName; }
            set { SetPropertyValue<string>(nameof(CustomerName), ref fCustomerName, value); }
        }
        int fIsActive;
        [ColumnDbDefaultValue("((1))")]
        public int IsActive
        {
            get { return fIsActive; }
            set { SetPropertyValue<int>(nameof(IsActive), ref fIsActive, value); }
        }
        string fDescription;
        [Size(250)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
        string fAddress;
        [Size(250)]
        public string Address
        {
            get { return fAddress; }
            set { SetPropertyValue<string>(nameof(Address), ref fAddress, value); }
        }
        string fAddress2;
        [Size(250)]
        public string Address2
        {
            get { return fAddress2; }
            set { SetPropertyValue<string>(nameof(Address2), ref fAddress2, value); }
        }
        double fBalanceTL;
        [ColumnDbDefaultValue("((0))")]
        public double BalanceTL
        {
            get { return fBalanceTL; }
            set { SetPropertyValue<double>(nameof(BalanceTL), ref fBalanceTL, value); }
        }
        int fCustomerGroupID;
        [Indexed(Name = @"Idx_GroupID")]
        public int CustomerGroupID
        {
            get { return fCustomerGroupID; }
            set { SetPropertyValue<int>(nameof(CustomerGroupID), ref fCustomerGroupID, value); }
        }
    }

}
