//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace MaSoft.MaPos.Models.MaPos
{

    public partial class Personnal : XPLiteObject
    {
        int fRowID;
        [Key(true)]
        public int RowID
        {
            get { return fRowID; }
            set { SetPropertyValue<int>(nameof(RowID), ref fRowID, value); }
        }
        DateTime fRowAddDateTime;
        public DateTime RowAddDateTime
        {
            get { return fRowAddDateTime; }
            set { SetPropertyValue<DateTime>(nameof(RowAddDateTime), ref fRowAddDateTime, value); }
        }
        int fRowAddUserNo;
        public int RowAddUserNo
        {
            get { return fRowAddUserNo; }
            set { SetPropertyValue<int>(nameof(RowAddUserNo), ref fRowAddUserNo, value); }
        }
        DateTime fRowEditDateTime;
        public DateTime RowEditDateTime
        {
            get { return fRowEditDateTime; }
            set { SetPropertyValue<DateTime>(nameof(RowEditDateTime), ref fRowEditDateTime, value); }
        }
        int fRowEditUserNo;
        public int RowEditUserNo
        {
            get { return fRowEditUserNo; }
            set { SetPropertyValue<int>(nameof(RowEditUserNo), ref fRowEditUserNo, value); }
        }
        int fID;
        [Indexed(Name = @"Idx_Id", Unique = true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }
        DateTime fWorkStartDate;
        public DateTime WorkStartDate
        {
            get { return fWorkStartDate; }
            set { SetPropertyValue<DateTime>(nameof(WorkStartDate), ref fWorkStartDate, value); }
        }
        int fWorkStatus;
        [ColumnDbDefaultValue("((1))")]
        public int WorkStatus
        {
            get { return fWorkStatus; }
            set { SetPropertyValue<int>(nameof(WorkStatus), ref fWorkStatus, value); }
        }
        string fGroupName;
        [Size(25)]
        public string GroupName
        {
            get { return fGroupName; }
            set { SetPropertyValue<string>(nameof(GroupName), ref fGroupName, value); }
        }
        string fJob;
        [Size(50)]
        public string Job
        {
            get { return fJob; }
            set { SetPropertyValue<string>(nameof(Job), ref fJob, value); }
        }
        int fSalary;
        public int Salary
        {
            get { return fSalary; }
            set { SetPropertyValue<int>(nameof(Salary), ref fSalary, value); }
        }
        int fIsUsingSystem;
        [ColumnDbDefaultValue("((1))")]
        public int IsUsingSystem
        {
            get { return fIsUsingSystem; }
            set { SetPropertyValue<int>(nameof(IsUsingSystem), ref fIsUsingSystem, value); }
        }
        string fPassword;
        [Size(50)]
        public string Password
        {
            get { return fPassword; }
            set { SetPropertyValue<string>(nameof(Password), ref fPassword, value); }
        }
        string fDescription;
        [Size(250)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
        string fPersonnalName;
        [Indexed(Name = @"Idx_PersonallName", Unique = true)]
        [Size(25)]
        public string PersonnalName
        {
            get { return fPersonnalName; }
            set { SetPropertyValue<string>(nameof(PersonnalName), ref fPersonnalName, value); }
        }
    }

}
