//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace MaSoft.MaPos.Models.MaPos
{

    public partial class PrintTask : XPLiteObject
    {
        int fRowID;
        [Key(true)]
        public int RowID
        {
            get { return fRowID; }
            set { SetPropertyValue<int>(nameof(RowID), ref fRowID, value); }
        }
        DateTime fRowAddDateTime;
        public DateTime RowAddDateTime
        {
            get { return fRowAddDateTime; }
            set { SetPropertyValue<DateTime>(nameof(RowAddDateTime), ref fRowAddDateTime, value); }
        }
        int fRowAddUserNo;
        public int RowAddUserNo
        {
            get { return fRowAddUserNo; }
            set { SetPropertyValue<int>(nameof(RowAddUserNo), ref fRowAddUserNo, value); }
        }
        DateTime fRowEditDateTime;
        public DateTime RowEditDateTime
        {
            get { return fRowEditDateTime; }
            set { SetPropertyValue<DateTime>(nameof(RowEditDateTime), ref fRowEditDateTime, value); }
        }
        int fRowEditUserNo;
        public int RowEditUserNo
        {
            get { return fRowEditUserNo; }
            set { SetPropertyValue<int>(nameof(RowEditUserNo), ref fRowEditUserNo, value); }
        }
        int fId;
        [Indexed(Name = @"Idx_Id", Unique = true)]
        [ColumnDbDefaultValue("((0))")]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>(nameof(Id), ref fId, value); }
        }
        string fDescription;
        [Size(250)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
        string fPrinterName;
        [Size(50)]
        public string PrinterName
        {
            get { return fPrinterName; }
            set { SetPropertyValue<string>(nameof(PrinterName), ref fPrinterName, value); }
        }
        string fProductName;
        [Indexed(Name = @"Idx_ProductId")]
        [Size(50)]
        public string ProductName
        {
            get { return fProductName; }
            set { SetPropertyValue<string>(nameof(ProductName), ref fProductName, value); }
        }
        string fProductGroup;
        [Indexed(Name = @"Idx_ProductGroupID")]
        [Size(50)]
        public string ProductGroup
        {
            get { return fProductGroup; }
            set { SetPropertyValue<string>(nameof(ProductGroup), ref fProductGroup, value); }
        }
        string fTerminalName;
        [Indexed(Name = @"Idx_TermId")]
        [Size(50)]
        public string TerminalName
        {
            get { return fTerminalName; }
            set { SetPropertyValue<string>(nameof(TerminalName), ref fTerminalName, value); }
        }
        string fDepartmentName;
        [Indexed(Name = @"Idx_DepId")]
        [Size(50)]
        public string DepartmentName
        {
            get { return fDepartmentName; }
            set { SetPropertyValue<string>(nameof(DepartmentName), ref fDepartmentName, value); }
        }
    }

}
