//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace MaSoft.MaPos.Models.MaPos
{

    [Indices(@"PortionId", "ProductId")]
    public partial class ProductPrices : XPLiteObject
    {
        int fRowID;
        [Key(true)]
        public int RowID
        {
            get { return fRowID; }
            set { SetPropertyValue<int>(nameof(RowID), ref fRowID, value); }
        }
        DateTime fRowAddDateTime;
        public DateTime RowAddDateTime
        {
            get { return fRowAddDateTime; }
            set { SetPropertyValue<DateTime>(nameof(RowAddDateTime), ref fRowAddDateTime, value); }
        }
        int fRowAddUserNo;
        public int RowAddUserNo
        {
            get { return fRowAddUserNo; }
            set { SetPropertyValue<int>(nameof(RowAddUserNo), ref fRowAddUserNo, value); }
        }
        DateTime fRowEditDateTime;
        public DateTime RowEditDateTime
        {
            get { return fRowEditDateTime; }
            set { SetPropertyValue<DateTime>(nameof(RowEditDateTime), ref fRowEditDateTime, value); }
        }
        int fRowEditUserNo;
        public int RowEditUserNo
        {
            get { return fRowEditUserNo; }
            set { SetPropertyValue<int>(nameof(RowEditUserNo), ref fRowEditUserNo, value); }
        }
        int fId;
        [Indexed(Name = @"Idx_Id", Unique = true)]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>(nameof(Id), ref fId, value); }
        }
        int fProductId;
        [Indexed(@"PortionId", Name = @"Idx_ProductAndPortId", Unique = true)]
        public int ProductId
        {
            get { return fProductId; }
            set { SetPropertyValue<int>(nameof(ProductId), ref fProductId, value); }
        }
        int fPortionId;
        public int PortionId
        {
            get { return fPortionId; }
            set { SetPropertyValue<int>(nameof(PortionId), ref fPortionId, value); }
        }
        float fSaloonPrice;
        [ColumnDbDefaultValue("((0))")]
        public float SaloonPrice
        {
            get { return fSaloonPrice; }
            set { SetPropertyValue<float>(nameof(SaloonPrice), ref fSaloonPrice, value); }
        }
        float fPackagedPrice;
        [ColumnDbDefaultValue("((0))")]
        public float PackagedPrice
        {
            get { return fPackagedPrice; }
            set { SetPropertyValue<float>(nameof(PackagedPrice), ref fPackagedPrice, value); }
        }
        float fSelfServicePrice;
        [ColumnDbDefaultValue("((0))")]
        public float SelfServicePrice
        {
            get { return fSelfServicePrice; }
            set { SetPropertyValue<float>(nameof(SelfServicePrice), ref fSelfServicePrice, value); }
        }
        float fHappyHourPrice;
        [ColumnDbDefaultValue("((0))")]
        public float HappyHourPrice
        {
            get { return fHappyHourPrice; }
            set { SetPropertyValue<float>(nameof(HappyHourPrice), ref fHappyHourPrice, value); }
        }
        float fFifthPrice;
        [ColumnDbDefaultValue("((0))")]
        public float FifthPrice
        {
            get { return fFifthPrice; }
            set { SetPropertyValue<float>(nameof(FifthPrice), ref fFifthPrice, value); }
        }
        float fSixthPrice;
        [ColumnDbDefaultValue("((0))")]
        public float SixthPrice
        {
            get { return fSixthPrice; }
            set { SetPropertyValue<float>(nameof(SixthPrice), ref fSixthPrice, value); }
        }
        float fSeventhPrice;
        [ColumnDbDefaultValue("((0))")]
        public float SeventhPrice
        {
            get { return fSeventhPrice; }
            set { SetPropertyValue<float>(nameof(SeventhPrice), ref fSeventhPrice, value); }
        }
    }

}
