//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace MaSoft.MaPos.Models.MaPos
{

    public partial class ProductGroup : XPLiteObject
    {
        int fRowID;
        [Key(true)]
        public int RowID
        {
            get { return fRowID; }
            set { SetPropertyValue<int>(nameof(RowID), ref fRowID, value); }
        }
        DateTime fRowAddDateTime;
        public DateTime RowAddDateTime
        {
            get { return fRowAddDateTime; }
            set { SetPropertyValue<DateTime>(nameof(RowAddDateTime), ref fRowAddDateTime, value); }
        }
        int fRowAddUserNo;
        public int RowAddUserNo
        {
            get { return fRowAddUserNo; }
            set { SetPropertyValue<int>(nameof(RowAddUserNo), ref fRowAddUserNo, value); }
        }
        DateTime fRowEditDateTime;
        public DateTime RowEditDateTime
        {
            get { return fRowEditDateTime; }
            set { SetPropertyValue<DateTime>(nameof(RowEditDateTime), ref fRowEditDateTime, value); }
        }
        int fRowEditUserNo;
        public int RowEditUserNo
        {
            get { return fRowEditUserNo; }
            set { SetPropertyValue<int>(nameof(RowEditUserNo), ref fRowEditUserNo, value); }
        }
        int fId;
        [Indexed(Name = @"Id", Unique = true)]
        [ColumnDbDefaultValue("((1))")]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>(nameof(Id), ref fId, value); }
        }
        string fProductGroup1;
        [Indexed(Name = @"Idx_GroupName")]
        [Size(50)]
        [Persistent(@"ProductGroup")]
        public string ProductGroup1
        {
            get { return fProductGroup1; }
            set { SetPropertyValue<string>(nameof(ProductGroup1), ref fProductGroup1, value); }
        }
        int fUpGroupId;
        [Indexed(Name = @"Idx_UpId")]
        public int UpGroupId
        {
            get { return fUpGroupId; }
            set { SetPropertyValue<int>(nameof(UpGroupId), ref fUpGroupId, value); }
        }
        int fIsVisibleForPos;
        public int IsVisibleForPos
        {
            get { return fIsVisibleForPos; }
            set { SetPropertyValue<int>(nameof(IsVisibleForPos), ref fIsVisibleForPos, value); }
        }
        int fUnitInfo;
        [ColumnDbDefaultValue("((0))")]
        public int UnitInfo
        {
            get { return fUnitInfo; }
            set { SetPropertyValue<int>(nameof(UnitInfo), ref fUnitInfo, value); }
        }
        string fColorName;
        [Size(20)]
        public string ColorName
        {
            get { return fColorName; }
            set { SetPropertyValue<string>(nameof(ColorName), ref fColorName, value); }
        }
        int fIsActivated;
        [ColumnDbDefaultValue("((1))")]
        public int IsActivated
        {
            get { return fIsActivated; }
            set { SetPropertyValue<int>(nameof(IsActivated), ref fIsActivated, value); }
        }
        byte[] fGroupImage;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] GroupImage
        {
            get { return fGroupImage; }
            set { SetPropertyValue<byte[]>(nameof(GroupImage), ref fGroupImage, value); }
        }
        int fMillId;
        [Indexed(Name = @"Idx_MillId")]
        public int MillId
        {
            get { return fMillId; }
            set { SetPropertyValue<int>(nameof(MillId), ref fMillId, value); }
        }
    }

}
