//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace MaSoft.MaPos.Models.MaPos
{

    public partial class ProgramSettings : XPLiteObject
    {
        int fRowID;
        [Key(true)]
        public int RowID
        {
            get { return fRowID; }
            set { SetPropertyValue<int>(nameof(RowID), ref fRowID, value); }
        }
        DateTime fRowAddDateTime;
        public DateTime RowAddDateTime
        {
            get { return fRowAddDateTime; }
            set { SetPropertyValue<DateTime>(nameof(RowAddDateTime), ref fRowAddDateTime, value); }
        }
        int fRowAddUserNo;
        public int RowAddUserNo
        {
            get { return fRowAddUserNo; }
            set { SetPropertyValue<int>(nameof(RowAddUserNo), ref fRowAddUserNo, value); }
        }
        DateTime fRowEditDateTime;
        public DateTime RowEditDateTime
        {
            get { return fRowEditDateTime; }
            set { SetPropertyValue<DateTime>(nameof(RowEditDateTime), ref fRowEditDateTime, value); }
        }
        int fRowEditUserNo;
        public int RowEditUserNo
        {
            get { return fRowEditUserNo; }
            set { SetPropertyValue<int>(nameof(RowEditUserNo), ref fRowEditUserNo, value); }
        }
        string fCompanyName;
        [Size(250)]
        public string CompanyName
        {
            get { return fCompanyName; }
            set { SetPropertyValue<string>(nameof(CompanyName), ref fCompanyName, value); }
        }
        string fBrandName;
        [Size(250)]
        public string BrandName
        {
            get { return fBrandName; }
            set { SetPropertyValue<string>(nameof(BrandName), ref fBrandName, value); }
        }
        string fAddress;
        [Size(250)]
        public string Address
        {
            get { return fAddress; }
            set { SetPropertyValue<string>(nameof(Address), ref fAddress, value); }
        }
        string fPostOffice;
        [Size(10)]
        public string PostOffice
        {
            get { return fPostOffice; }
            set { SetPropertyValue<string>(nameof(PostOffice), ref fPostOffice, value); }
        }
        string fCity;
        [Size(50)]
        public string City
        {
            get { return fCity; }
            set { SetPropertyValue<string>(nameof(City), ref fCity, value); }
        }
        string fTown;
        [Size(50)]
        public string Town
        {
            get { return fTown; }
            set { SetPropertyValue<string>(nameof(Town), ref fTown, value); }
        }
        string fCountry;
        [Size(50)]
        public string Country
        {
            get { return fCountry; }
            set { SetPropertyValue<string>(nameof(Country), ref fCountry, value); }
        }
        string fTaxNumber;
        [Size(20)]
        public string TaxNumber
        {
            get { return fTaxNumber; }
            set { SetPropertyValue<string>(nameof(TaxNumber), ref fTaxNumber, value); }
        }
        string fTaxOffice;
        public string TaxOffice
        {
            get { return fTaxOffice; }
            set { SetPropertyValue<string>(nameof(TaxOffice), ref fTaxOffice, value); }
        }
        string fRelevantPerson;
        [Size(50)]
        public string RelevantPerson
        {
            get { return fRelevantPerson; }
            set { SetPropertyValue<string>(nameof(RelevantPerson), ref fRelevantPerson, value); }
        }
        string fTelephone1;
        [Size(50)]
        public string Telephone1
        {
            get { return fTelephone1; }
            set { SetPropertyValue<string>(nameof(Telephone1), ref fTelephone1, value); }
        }
        string fTelephone2;
        [Size(50)]
        public string Telephone2
        {
            get { return fTelephone2; }
            set { SetPropertyValue<string>(nameof(Telephone2), ref fTelephone2, value); }
        }
        string fCellTelephone;
        [Size(50)]
        public string CellTelephone
        {
            get { return fCellTelephone; }
            set { SetPropertyValue<string>(nameof(CellTelephone), ref fCellTelephone, value); }
        }
        string fFax;
        [Size(50)]
        public string Fax
        {
            get { return fFax; }
            set { SetPropertyValue<string>(nameof(Fax), ref fFax, value); }
        }
        string feMail;
        [Size(50)]
        public string eMail
        {
            get { return feMail; }
            set { SetPropertyValue<string>(nameof(eMail), ref feMail, value); }
        }
        string fWeb;
        [Size(50)]
        public string Web
        {
            get { return fWeb; }
            set { SetPropertyValue<string>(nameof(Web), ref fWeb, value); }
        }
        byte[] fCompanyLogo;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] CompanyLogo
        {
            get { return fCompanyLogo; }
            set { SetPropertyValue<byte[]>(nameof(CompanyLogo), ref fCompanyLogo, value); }
        }
        int fDefaultMoneyUnit;
        [ColumnDbDefaultValue("((0))")]
        public int DefaultMoneyUnit
        {
            get { return fDefaultMoneyUnit; }
            set { SetPropertyValue<int>(nameof(DefaultMoneyUnit), ref fDefaultMoneyUnit, value); }
        }
        int fDefaultLanguage;
        [ColumnDbDefaultValue("((0))")]
        public int DefaultLanguage
        {
            get { return fDefaultLanguage; }
            set { SetPropertyValue<int>(nameof(DefaultLanguage), ref fDefaultLanguage, value); }
        }
        int fScaleMenstrualFlag;
        [ColumnDbDefaultValue("((25))")]
        public int ScaleMenstrualFlag
        {
            get { return fScaleMenstrualFlag; }
            set { SetPropertyValue<int>(nameof(ScaleMenstrualFlag), ref fScaleMenstrualFlag, value); }
        }
        int fScaleHoldingFlag;
        [ColumnDbDefaultValue("((24))")]
        public int ScaleHoldingFlag
        {
            get { return fScaleHoldingFlag; }
            set { SetPropertyValue<int>(nameof(ScaleHoldingFlag), ref fScaleHoldingFlag, value); }
        }
        int fScaleWeighingCode3;
        [ColumnDbDefaultValue("((29))")]
        public int ScaleWeighingCode3
        {
            get { return fScaleWeighingCode3; }
            set { SetPropertyValue<int>(nameof(ScaleWeighingCode3), ref fScaleWeighingCode3, value); }
        }
        int fScaleWeighingCode2;
        [ColumnDbDefaultValue("((28))")]
        public int ScaleWeighingCode2
        {
            get { return fScaleWeighingCode2; }
            set { SetPropertyValue<int>(nameof(ScaleWeighingCode2), ref fScaleWeighingCode2, value); }
        }
        int fScaleWeighingCode1;
        [ColumnDbDefaultValue("((27))")]
        public int ScaleWeighingCode1
        {
            get { return fScaleWeighingCode1; }
            set { SetPropertyValue<int>(nameof(ScaleWeighingCode1), ref fScaleWeighingCode1, value); }
        }
        string fBranch;
        [Size(50)]
        public string Branch
        {
            get { return fBranch; }
            set { SetPropertyValue<string>(nameof(Branch), ref fBranch, value); }
        }
        int fEInvoiceCompany;
        [ColumnDbDefaultValue("((0))")]
        public int EInvoiceCompany
        {
            get { return fEInvoiceCompany; }
            set { SetPropertyValue<int>(nameof(EInvoiceCompany), ref fEInvoiceCompany, value); }
        }
        int fEInvoiceActivated;
        [ColumnDbDefaultValue("((0))")]
        public int EInvoiceActivated
        {
            get { return fEInvoiceActivated; }
            set { SetPropertyValue<int>(nameof(EInvoiceActivated), ref fEInvoiceActivated, value); }
        }
        int fSmsCompany;
        [ColumnDbDefaultValue("((0))")]
        public int SmsCompany
        {
            get { return fSmsCompany; }
            set { SetPropertyValue<int>(nameof(SmsCompany), ref fSmsCompany, value); }
        }
    }

}
